version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.4
  - dependency-name: webpack
    versions:
    - 5.34.0
