export const RESET_PASSWORD_ADMIN_REQUEST = '@@user/RESET_PASSWORD_ADMIN_REQUEST';
export const RESET_PASSWORD_ADMIN_SUCCESS = '@@user/RESET_PASSWORD_ADMIN_SUCCESS';
export const RESET_PASSWORD_ADMIN_ERROR = '@@user/RESET_PASSWORD_ADMIN_ERROR';
